name: 'OpenTelemetry Build Metrics'
description: 'generates OpenTelemetry build metrics for GitHub actions'
inputs:
  finalize:
    description: 'whether to finalize metrics'
    required: true
    default: false
  endpoint:
    description: 'GRPC endpoint of OpenTelemetry Collector'
    required: true
    default: "localhost:4317"
runs:
  using: 'node12'
  pre: 'dist/setup/index.js'
  post: 'dist/cleanup/index.js'
