name: 'OpenTelemetry Build Metrics'
description: 'generates OpenTelemetry build metrics for GitHub actions'
inputs:
  finalize:
    description: 'whether to finalize metrics'
    required: true
    default: false
outputs:
  jobStartTimestamp:
    description: 'starting timestamp (in ms) for job'
runs:
  using: 'node12'
  pre: 'dist/setup/index.js'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'
