on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: loomis/build-metrics@main
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Get the output time
      run: echo "END OF JOB1"
  goodbye_world_job:
    runs-on: ubuntu-20.04
    name: A job to say goodbye
    steps:
    - name: Hello world action step
      id: hello
      uses: loomis/build-metrics@main
      with:
        who-to-greet: 'John the Bard'
    - name: Get the output time
      run: echo "END OF JOB 2"
