on: [push]

jobs:
  initialize:
    runs-on: ubuntu-20.04
    steps:
      - uses: loomis/build-metrics@main
  job1:
    needs: initialize
    runs-on: ubuntu-20.04
    steps:
      - uses: loomis/build-metrics@main
      - run: echo "END OF JOB 1"
      - uses: loomis/build-metrics@main
        with:
          finalize: false
  job2:
    needs: initialize
    runs-on: ubuntu-20.04
    steps:
      - uses: loomis/build-metrics@main
      - run: echo "END OF JOB 2"
  finalize:
    if: always()
    needs: [job1, job2]
    runs-on: ubuntu-20.04
    steps:
      - uses: loomis/build-metrics@main
        with:
          finalize: true
